
[[constraint]]
  name = "github.com/docker/go-connections"
  version = "0.4.0"

[[constraint]]
  name = "github.com/docker/docker"
  version = "1.13.1"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.5.0"
